name: Benchmarks

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]
        platform:
          - os: ubuntu-latest
            shell: bash
          - os: macos-latest
            shell: bash
          - os: windows-latest
            shell: bash
      fail-fast: false

    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use latest npm
        run: npm i -g npm@latest

      - name: Install dependencies
        run: npm install

      - name: Run Benchmarks
        run: npm run benchmark
